name: yuva
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI/UX
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  shimmer: ^3.0.0
  animated_background: ^2.0.0
  blur: ^3.1.0
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.3.1

  # Firebase (All updated to v3 compatible versions)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_database: ^11.0.2
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+5



  # State Management
  provider: ^6.1.1

  # Others
  shared_preferences: ^2.2.2
  pin_code_fields: ^8.0.1
  intl: ^0.19.0  # Added for DateFormat
  image_picker: ^1.0.4 # or the latest version
  permission_handler: ^11.3.1
  device_info_plus: ^9.0.0  # Use the latest version
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_image_compress: ^2.0.0
  video_compress: ^3.1.2
  fluttertoast: ^8.2.2
  photo_view: ^0.14.0
  video_player: ^2.9.1
  chewie: ^1.8.1 # For better video player controls
  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.4
  font_awesome_flutter: ^10.5.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/illustrations/Happy student-bro.svg
    - assets/lottie/yuva_launch.json
    - assets/lottie/intro1.json
    - assets/lottie/intro2.json
    - assets/lottie/intro3.json
    - assets/lottie/intro4.json
    - assets/default_profile.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
