// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1YfSIseFuDn125j3wjUfjkDEWugocMWU',
    appId: '1:796885332741:web:b99659a45f28e22187fd6c',
    messagingSenderId: '796885332741',
    projectId: 'yuvaapp',
    authDomain: 'yuvaapp.firebaseapp.com',
    databaseURL: 'https://yuvaapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yuvaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9vipneHfsLEXeBWTVPEawK77N2-vFW2s',
    appId: '1:796885332741:android:dda9003aa7bd4e6387fd6c',
    messagingSenderId: '796885332741',
    projectId: 'yuvaapp',
    databaseURL: 'https://yuvaapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yuvaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGGfKC0aBa8_60rG8IuCGYXXxbQuUo9Ms',
    appId: '1:796885332741:ios:5a1f6d332f463bee87fd6c',
    messagingSenderId: '796885332741',
    projectId: 'yuvaapp',
    databaseURL: 'https://yuvaapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yuvaapp.firebasestorage.app',
    iosBundleId: 'com.example.yuva',
  );

}